name: Update ZITADEL
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    name: update zitadel api
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          ## Workaround until https://github.com/docker/build-push-action/issues/252#issuecomment-804898823 is merged
          version: v0.6.0
          buildkitd-flags: --debug
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker build -f build/zitadel/Dockerfile . -o ./pkg/client
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-api
          draft: true
          base: main
