name: Update ZITADEL API
on:
  pull_request:
    branches-ignore:
      - '**'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - name: Source checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          ## Workaround until https://github.com/docker/build-push-action/issues/252#issuecomment-804898823 is merged
          version: v0.6.0
          buildkitd-flags: --debug
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/zitadel/Dockerfile
          outputs: type=local,dest=./pkg/client
          platforms: linux/amd64
          build-args: |
            PROJECT_PATH=github.com/caos/zitadel-go/pkg/client
      - uses: actions/upload-artifact@v2
        with:
          name: zitadel-go
          path: ./
